### ISSUE TITLE
Show "VoxxedDays" as title when voxxed is selected

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#111]
When selecting Voxxed, the title still shows "Devoxx""

![image](https://user-images.githubusercontent.com/179457/45409081-7fb49900-b66e-11e8-960f-8da901ee1495.png)

**Comment by abhinayagarwal** [comment]
@stephanj Devoxx has a tag line - "From Developers, For Developers". Do we have something similar for VoxxedDays?

**Comment by tiainen** [comment]
@abhinayagarwal when looking at voxxeddays.com the tagline appears to be the same for both.
