### ISSUE TITLE
Use cached JSON files to get future Devoxx/Voxxed events

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#112]
Use the cached JSON files to collect the future Devoxx and VoxxedDays events.

https://s3-eu-west-1.amazonaws.com/thewebsites/futureDevoxx.json
https://s3-eu-west-1.amazonaws.com/thewebsites/futureVoxxed.json

Because the actual REST call can be slow which results in an empty home page as shown below.

![image](https://user-images.githubusercontent.com/179457/45409153-affc3780-b66e-11e8-85ff-ef49de139e3e.png)

**Comment by abhinayagarwal** [comment]
Hi @stephanj ,

Just wondering if you do not see a ProgressIndicator at the center of the view while the conferences are being loaded.

**Comment by tiainen** [comment]
@abhinayagarwal Stephan enabled http caching in the voxxed backend and we've implemented a caching mechanism for cloudlink remote functions that make use of that information. All four remote functions that call into the voxxed backend are configured with caching enabled. Please test.

**Comment by tiainen** [comment]
For caching, we now rely on the http response headers cache-control and etag.
