### ISSUE TITLE
Show past events on home page

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#117]
Show past events, similar like the Devoxx and VoxxedDays home page would be nice.

The following cached JSON file gives you a list of the past events.
https://s3-eu-west-1.amazonaws.com/thewebsites/pastEvents.json 

Allowing mobile users to view past events (including CFP details) would be a nice feature to have.
It would also allow us to test scheduled data etc.

**Comment by abhinayagarwal** [comment]
Some of the conferences in the json (for example conference id 13, 17, 19 etc.) have `cfpURL` returned as empty or null.

Since the cfpURL is fetched once the user has selected the conference this can be a real problem.

**Comment by abhinayagarwal** [comment]
Should we create a new section in the NavigationDrawer for this?

The conference selector is very busy and adding another option to the same view might not be a very good option. Although, I would like to know if someone has any other idea(s).

Images for both are added below:

<img alt="nd" src="https://user-images.githubusercontent.com/3197675/45733855-dc302f00-bbff-11e8-8c5e-89d3690a686e.png" width=300>
<img alt="conference" src="https://user-images.githubusercontent.com/3197675/45733948-3b8e3f00-bc00-11e8-8f15-89cfb6724851.jpeg" width=300>

**Comment by stephanj** [comment]
I would show "Past events" next to "Devoxx" and "VoxxedDayx" menu items when selecting the filter icon.  As shown below.

![image](https://user-images.githubusercontent.com/179457/45752291-46070380-bc15-11e8-84f8-12183ef2258c.png)

**Comment by abhinayagarwal** [comment]
Fixed by #122
