### ISSUE TITLE
Duplicate entry in past conferences

### ISSUE THREAD

**Issue by abhinayagarwal** [devoxx/MyDevoxxGluon#129]
Devoxx UK 2018 is present for id's 21 and 45 in past conferences fetched from https://api.voxxed.com/api/voxxeddays/events/past

**Comment by stephanj** [comment]
Fixed

**Comment by abhinayagarwal** [comment]
Hi @stephanj,

What exactly is a MEETUP event type?

For id=45 and name = "Devoxx UK 2018", the eventType has been updated to MEETUP. 

Do we need to show this on the app or can we filter events where event type is MEETUP?
