### ISSUE TITLE
Track name stretch Session cells

### ISSUE THREAD

**Issue by abhinayagarwal** [devoxx/MyDevoxxGluon#131]
With Devoxx BE 2018, few track names were introduced which are very large and stretch the session cells. Please check the image below:

<img alt="devoxx_track_name" src="https://user-images.githubusercontent.com/3197675/46014419-cbdeef00-c0ec-11e8-8008-1185193db687.png" width=300>

This doesn't look very appealing. 

I have a few suggestions:

* Keep a max size per cell or max length for track string. This will avoid excessive large cells but will trim the track name. For example, "Cloud, Containers & Infrastructure" could become "Cloud, Containe..."
* Add short forms for track names. We could manually add short forms for track name. For example, a short form for "Big Data & Machine Learning" could be "Big Data & ML", and for "Java Language", it can be "Java Lang". I'm not sure what can be a suitable short form for "Cloud, Containers & Infrastructure". This technique is verbose, needs discussion and would require maintenance on every release.

If someone has any other suggestion, feel free to add it as a comment.

**Comment by stephanj** [comment]
The cells are indeed too big.  

I would strongly suggest to shorten the track names (or just cut them off). 

Nice to have: maybe show the colours also in the "Track filter" view (as shown below) ?

![image](https://user-images.githubusercontent.com/179457/46400861-ac9f1d80-c6fb-11e8-9f67-440954272e4c.png)
