### ISSUE TITLE
Update copy references to Devoxx to a more generic sentence

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#133]
Please change the "Exhibition Maps" sentence, this way it works for both Devoxx and Voxxed Days: 

"This view will show the exhibition maps.  Please Check back later."

![image](https://user-images.githubusercontent.com/179457/46028941-39414e80-c0f2-11e8-8fd7-16df7727983d.png)

**Comment by tiainen** [comment]
We can take a look at the copy and change every reference to Devoxx to a more generic term when possible. For instance, the Content Catalog view also has Devoxx in the placeholder sentence.

**Comment by abhinayagarwal** [comment]
@tiainen Should we make the message generic or should we update the conference type in the message as an optional parameter? 

This latter can be done inside the showing event of the view.

**Comment by tiainen** [comment]
I prefer to replace the sentences with ones that no longer have a reference to devoxx. I believe it adds no extra information to keep the reference.
