### ISSUE TITLE
Header in conference selector incorrectly shows Devoxx

### ISSUE THREAD

**Issue by tiainen** [devoxx/MyDevoxxGluon#134]
With the following use case, the header title in the conference selector incorrectly shows "Devoxx":

1. Open the application
2. Switch to the Voxxed Days conferences
3. Select a conference
4. Close the application
5. Open the application (the last selected conference should be loaded)
6. Navigate to the conference selector

The header now shows "Devoxx", while the ListView displays the Voxxed Days conferences.

**Comment by abhinayagarwal** [comment]
Should we always open conference selector with Devoxx by default?

The reason I suggest this is because imo users shouldn't see Past Events by default irrespective of their last selection being an event from the list of Past Events.

**Comment by jperedadnr** [comment]
That happens also if you close the app from a future Voxxed event. When you open it again, it should say Voxxed.

**Comment by tiainen** [comment]
I agree with @abhinayagarwal that it is the easiest if we open the Devoxx conferences by default whenever the conference selector view is shown.
