### ISSUE TITLE
Voxxed Days Ticino schedule is shown for Devoxx Belgium

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#135]
1) Look at the Voxxed Days Ticino schedule 
2) Switch conference and select Devoxx Belgium
3) You'll notice that the previous schedule is still shown

![image](https://user-images.githubusercontent.com/179457/46069243-638b1e80-c17b-11e8-9ba1-96101bc010b0.png)

![image](https://user-images.githubusercontent.com/179457/46069319-96cdad80-c17b-11e8-9b08-78905f006bf3.png)

**Comment by johanvos** [comment]
@stephanj can you confirm that the "previous" schedule (in this case Ticino) is only visible for not more than a few seconds?
If that is the case, PR #136 will fix it.
If not, there must be a different problem but we can't reproduce it -- hence before we dive into it, can you share your observations?
