### ISSUE TITLE
Hide item in menu if the organiser did not provide relevant info

### ISSUE THREAD

**Issue by mrhazell** [devoxx/MyDevoxxGluon#143]
Could we add an enhancement where items are hidden from menu if the organiser does not provide the required information?

The most relevant example will be 'Exhibition Maps'. Especially for Voxxed Days events where it is likely many organisers will not provide this.

**Comment by abhinayagarwal** [comment]
@mrhazell It actually depends where the required information is coming from. For example, for 'Exhibition Maps', we query the floor attribute in the conference data. We can use this information when a conference is fetched to hide the Exhibition Maps entry in the drawer.

This leaves us with only:

* Content Catalogue
* Speakers
* Venue
* My Notes
* My Badges (only enabled for Devoxx BE, FR and UK)
* About
* Conference Selector
* Logout (only shown when a user logs in)

Do you find any of the above items could be optional along with 'Exhibition Maps'?
