### ISSUE TITLE
Spinnner keeps on spinning

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#147]
Stopped the mobile app when Voxxed Days Bristol was selected.
When restarting the app, the spinner is shown for Voxxed Days Bristol but unfortunately it keeps on spinning (longer than 15 secs).

![image](https://user-images.githubusercontent.com/179457/46214325-2c636b80-c33b-11e8-83c6-9c724d306f27.png)

**Comment by jperedadnr** [comment]
Fixed by #151
