### ISSUE TITLE
Tracks are not shown for Devoxx Morocco

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#154]
Do keep in mind that Devoxx Morocco is using their own CFP instance (not the generic one), so the issue could be related to this.

Can you double check?

![image](https://user-images.githubusercontent.com/179457/46354698-7f049680-c65f-11e8-9ab1-07fc828729b0.png)

**Comment by erwin1** [comment]
@stephanj the app uses the tracks from this response https://api.voxxed.com/api/voxxeddays/events/ID

which is empty in case of Devoxx MA: https://api.voxxed.com/api/voxxeddays/events/37

**Comment by stephanj** [comment]
I've added the sessionTypes for Devoxx MA in the admin web app.

**Comment by stephanj** [comment]
Also added the exact same tracks the non-generic CFP uses.

![image](https://user-images.githubusercontent.com/179457/46399925-634dce80-c6f9-11e8-96fe-f5e0197ab94a.png)

**Comment by stephanj** [comment]
Works now
![image](https://user-images.githubusercontent.com/179457/46409208-f3e5d800-c714-11e8-9d7a-2f9cb1876eda.png)
