### ISSUE TITLE
Add Gamification to voting

### ISSUE THREAD

**Issue by abhinayagarwal** [devoxx/MyDevoxxGluon#156]
This is a subset of #41. The target of this issue is to empower users select either a compliment or an improvement based on the no of stars for a session while voting.

**Comment by erwin1** [comment]
I've tested the changes in your fork and found a blocking issue: 
- go to a talk
- go to vote
- go back (talk is shown)
- go back (vote dialog is shown again)

And there's no way to go back to the talk overview

**Comment by abhinayagarwal** [comment]
Can't you just dismiss the vote dialog by using the 'X' on the top left?

**Comment by abhinayagarwal** [comment]
@erwin1 I have updated the PR, could you test if the issue is fixed?

**Comment by erwin1** [comment]
Current texts:

rating stars:
1: Poor
2: Poor
3: Good
4: Good
5: Excellent

Predefined comments:

Improvements: (1 or 2 rating stars)
        HARD("Hard to understand")
        FAST("Too fast")
        DEMOS("Not enough demos/samples")
        COMPLICATED("Complicated")


Compliments (3, 4 or 5 rating stars)
        FUN("FUN!")
        DEMOS("I loved the demos")
        LEARNED_SOMETHING("Learned something new")
        INTERESTING("Very interesting")

**Comment by stephanj** [comment]
5 star ratings
* Awesome content
* Really enjoyed this
* Amazing speaker
* Devoxx Rock Star is born
* New Venkat in the making

**Comment by erwin1** [comment]
@abhinayagarwal I think it would be very nice to make the predefined comments remotely configurable (e.g. using a remote function with a mock response)

**Comment by abhinayagarwal** [comment]
Fixed by PR #153, #196, #198
