### ISSUE TITLE
On Android (Samsung S7 - Android 8.0.0) the app is blocked in the welcome screen (loading forever)

### ISSUE THREAD

**Issue by alexproca** [devoxx/MyDevoxxGluon#167]
![screenshot_20181010-135137](https://user-images.githubusercontent.com/252961/46731894-93b2e100-cc94-11e8-8c49-83ec19249694.jpg)

**Comment by erwin1** [comment]
Hi @alexproca 

Thanks for reporting. It was a misconfiguration and should be fixed now.

Thanks,
Erwin
