### ISSUE TITLE
QR Code can not be scanned by mobile app

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#175]
The "My Badge" doesn't scan the following QR Code.
However a regular QR Code Android app does read it.

![image](https://user-images.githubusercontent.com/179457/47255589-e00bd700-d473-11e8-9c60-fe57c59fbd7d.png)

**Comment by erwin1** [comment]
the QR seems to be lacking the ID. See https://github.com/devoxx/MyDevoxxGluon/blob/bbbb882d9d1ba74228ea64a3d03add418be6a11f/DevoxxClientCommon/src/main/java/com/devoxx/model/Badge.java#L42

The app expects: 
`ID::lastname::firstname::company::email`
