### ISSUE TITLE
Badge scanning problems in Voxxed Days Bristol

### ISSUE THREAD

**Issue by mrhazell** [devoxx/MyDevoxxGluon#182]
A few issues happening here.

1) Occasionally the QR code scan icon in the bottom right hand corner disappears.

2) The app does not remember me as a sponsor. Therefore, after I scan a badge, if I navigate to any other feature and then click My Badges again, I am required to choose which sponsor I belong to and re-enter the password

3) Getting stuck at 'Select sponsor' screen. Here, I have scanned a badge and clicked the back button in top left hand corner. It has taken me back to the list of sponsors, and from there I cannot go anywhere else. The only function available to me is to click into a sponsor name, re-enter password, and then navigate from the hamburger button in top left corner.

![screenshot_20181023-123040](https://user-images.githubusercontent.com/39952280/47358245-2144f680-d6c1-11e8-8467-dd7b05c00a0a.jpg)
![screenshot_20181023-123442](https://user-images.githubusercontent.com/39952280/47358246-22762380-d6c1-11e8-9b5b-d9a7b9a7bfca.jpg)

**Comment by abhinayagarwal** [comment]
Hi,

The reason for 2 is missing slug in all sponsor details - https://api.voxxed.com/api/voxxeddays/sponsors/38

Slug is a mandatory field and is also used as the primary key to store all badges in the backend.

**Comment by stephanj** [comment]
I've added the missing slugs and will become a required field in the next admin version.

**Comment by abhinayagarwal** [comment]
Hi Stephan,

Capgemini (id=52) still has slug as `null`. We have been thinking if it makes more sense to use the id instead of the slug.

**Comment by abhinayagarwal** [comment]
@mrhazell I have been trying to reproduce the issue with scan button as mentioned in 1 without success. If you find a pattern in its disappearance please let us know :)
