### ISSUE TITLE
Badge scanning fails on portrait mode and short distance

### ISSUE THREAD

**Issue by jperedadnr** [devoxx/MyDevoxxGluon#188]
On some devices, badge scanning fails on portrait mode, being close to the qr. Stepping back a little seems to help. Other QR readers work fine on short distance.

A possible fix is to launch the zxing activity on landscape mode (there is no need to rotate the device though).

**Comment by erwin1** [comment]
fixed by https://github.com/devoxx/MyDevoxxGluon/commit/e28da1177b4b6e1a6c939995fce853e03947c8d9
