### ISSUE TITLE
Show breaks in schedule

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#197]
It would be really nice if also the breaks are shown in the schedule.
Let me know what you need (extra) to make this happen?

**Comment by stephanj** [comment]
The follow REST endpoint now includes the break details, example @  https://dvbe18.confinabox.com/api/conferences/dvbe18/schedules/monday 

See also https://dvbe18.confinabox.com/byday/mon

**Comment by stephanj** [comment]
![image](https://user-images.githubusercontent.com/179457/47847709-5f7e9c00-ddcc-11e8-8eb7-c196f18f3c68.png)

**Comment by abhinayagarwal** [comment]
Some preliminary work with this issue and the following is what we have right now. Any feedback would be appreciated:

![image](https://user-images.githubusercontent.com/3197675/47916172-46104980-decb-11e8-852a-c6b9d23860d8.png)

Break has only start and end time. It has no characteristics of a Talk i.e. track or type. Therefore when using filter, for Track and Type, break is not shown any more. For Day and Time filters, it is only shown if it satisfies the criteria i.e. break day / start and end time.

**Comment by abhinayagarwal** [comment]
Fixed by PR #203 and #204
