### ISSUE TITLE
Ratings submit button is hidden on smaller screens

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#214]
Some smartphones with smaller screens can't submit their rating because the submit button is hidden in the footer of the screen and they can't scroll down.

Maybe we should place the submit button (also?) in the header on the right?

![image](https://user-images.githubusercontent.com/179457/48767707-96ebb480-ecb7-11e8-9e35-32e3dcf30cce.png)

**Comment by stephanj** [comment]
Was on a Sony Xperia Z5 Compact device

![image](https://user-images.githubusercontent.com/179457/48767848-ed58f300-ecb7-11e8-985c-0c3931369ec5.png)

**Comment by 3mek** [comment]
Same for apple iphone SE (A2296).
