### ISSUE TITLE
Show presentation language (flag)

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#219]
If the event has multiple language presentations then showing the language flag would be very interesting to see for attendees.

**Comment by abhinayagarwal** [comment]
Hi Stephan,

Where do you want to show the language flag? On the sessions catalogue view or on the session description view?

Also, which flag do you want to show for English? 
![image](https://user-images.githubusercontent.com/3197675/54535563-c8019a80-49b4-11e9-90f4-c0274c57e308.png)

**Comment by stephanj** [comment]
Let's go for the UK flag for English and I would start adding the flag on the session description view for now.

**Comment by abhinayagarwal** [comment]
Hi Stephan,

Here are some examples of placement of the flag in session description view. Please share your feedback on the same..

<img src="https://user-images.githubusercontent.com/3197675/54550773-b3cc9600-49d2-11e9-8a48-e7a71dac7f50.PNG" height=400px/><img src="https://user-images.githubusercontent.com/3197675/54550775-b3cc9600-49d2-11e9-910c-c8d62ae4a796.PNG" height=400px/>

<img src= "https://user-images.githubusercontent.com/3197675/54550776-b4652c80-49d2-11e9-8744-463adc6f278d.PNG" height=400px/><img src= "https://user-images.githubusercontent.com/3197675/54550779-b4652c80-49d2-11e9-9e6e-471ad746774d.PNG" height=400px/>

<img src= "https://user-images.githubusercontent.com/3197675/54550783-b4fdc300-49d2-11e9-9001-7d839ee7fd85.PNG" height=400px/>

<img src= "https://user-images.githubusercontent.com/3197675/54550790-b7601d00-49d2-11e9-939b-be509f05a588.PNG" height=400px/><img src= "https://user-images.githubusercontent.com/3197675/54550791-b7f8b380-49d2-11e9-8bf0-2a2d9848f9ff.PNG" height=400px/>
