### ISSUE TITLE
Switch the admin.voxxed.com domain to www.devoxxians.com

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#221]
The admin backend application will be replaced by a brand new release which is available @ www.devoxxians.com . 

This new domain name should be used to retrieve the past and future events.

**Comment by stephanj** [comment]
BTW the cfpURL JSON parameter is replaced with apiURL

**Comment by erwin1** [comment]
full paths:
* devoxx: /api/public/events/future/devoxx
* voxxed: /api/public/events/future/voxxed
* all upcoming: /api/public/events/upcoming
* all past: /api/public/events/past

note: make sure to exclude conferences without apiURL in all 4 cases.
