### ISSUE TITLE
Include badge scan timestamp in export

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#236]
It would be really useful to include a timestamp of the actual scan. 
This would allow you to include this timestamp in the CSV export.

Because now we've discussions with a sponsor that she thinks not all scans are included in her list, having the timestamp included would resolve this discussion.

**Comment by erwin1** [comment]
* include scan datetime in (locally stored) Badge
* include datetime in local export

**Comment by abhinayagarwal** [comment]
Do we want to store the timestamp for just sponsor badges or for both attendee/sponsors ?

**Comment by abhinayagarwal** [comment]
PR merged with timestamp for sponsor badges.
