### ISSUE TITLE
Title not shown because of emoji

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#305]
Title not shown because of emoji at the beginning of the title.

![image](https://user-images.githubusercontent.com/179457/168243974-8cb79970-eb86-40df-bd2d-d34944b9dff6.png)

![image](https://user-images.githubusercontent.com/179457/168244043-07da91f8-f66e-420e-8f0a-62be915aaf5a.png)

**Comment by jperedadnr** [comment]
Fixed with #308
