### ISSUE TITLE
Support new QR Code 

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#323]
We've been requested to add also the country of the attendee in the QR Code (see example attached).  Could you please update the Badges Scanner app to also support this?

![Example](https://user-images.githubusercontent.com/179457/184110524-d8697d40-b923-41d3-ae9b-b7cd1466619e.jpg)

**Comment by jperedadnr** [comment]
The latest TestFlight version (1.0 - 115) already supports this. Can you test it?

**Comment by stephanj** [comment]
My bad... new version works with country code. Thanks!
