### ISSUE TITLE
App not run on Android 11+ successful when build with targetSdkVersion 30

### ISSUE THREAD

**Issue by ctoabidmaqbool** [devoxx/MyDevoxxGluon#326]
Have anyone tried by building android apk with **targetSdkVersion 30** for proper supports for **Android 11+** devices.

If I build app for targetSdkVersion 29 or before App will be run on Android 11 too. But I am more likely to build app for targetSdkVersion 30 due to some requirement.

What will be the steps to successful run?

Please! Helps me I am trying to achieve this in my another app.

**Comment by ctoabidmaqbool** [comment]
Moreover, I have created final APK using this method:

```
gradle clean apkDebug

zipalign -p -f -v 4 DevoxxClient-unaligned.apk "Devoxx Client.apk"

apksigner sign --ks Key.keystore --ks-pass file:Pass.txt --v1-signing-enabled true --v2-signing-enabled true "Devoxx Client.apk"

apksigner verify "Devoxx Client.apk"
```

**Comment by ctoabidmaqbool** [comment]
Output of `adb logcat *:E -d > logs/logcat-error.log`

[logcat-error.log](https://github.com/devoxx/MyDevoxxGluon/files/9539574/logcat-error.log)

And `adb logcat -d > logs/logcat.log`

[logcat.log](https://github.com/devoxx/MyDevoxxGluon/files/9539573/logcat.log)

**Comment by ctoabidmaqbool** [comment]
Another guy having the same issue in his project!
https://www.anycodings.com/questions/problem-when-update-targetsdkversion-to-30-dalvik-javafx

**Comment by jperedadnr** [comment]
Are you using this branch https://github.com/devoxx/MyDevoxxGluon/tree/gluonfx ?

**Comment by ctoabidmaqbool** [comment]
@jperedadnr Hi! I am using latest master branch for testing
![image](https://user-images.githubusercontent.com/10474725/189595341-02d62e32-e2ee-4032-ad20-2e01d6ab4a04.png)

targetsdk 29 works
targetsdk 30 not

**Comment by jperedadnr** [comment]
Master branch still uses the JavaFXPorts plugin which is EOL and not longer maintained. There are no recent commits in this branch.
The `gluonfx` branch uses the GluonFX plugin, which by default sets target 30. This branch is currently the one under development.

**Comment by ctoabidmaqbool** [comment]
@jperedadnr Hi! I have tried many time of new plugin e.g. GluonFx. Still It's not usable in my case (many libraries are not working still in graalvm). 

Actually my Android project is little bit complex... Still I am pretty satisfied with old plugin with javafxports.

Can you still help me to solve the issue?

**Comment by ctoabidmaqbool** [comment]
My app works fine with no issue on Android 11+ if I build apk using targetSdk 29
but can't upload to playstore (it needs target sdk 30)

**Comment by jperedadnr** [comment]
Check this post: https://stackoverflow.com/a/55970138/3956070, it seems it has a different fix for 30.

**Comment by ctoabidmaqbool** [comment]
A lot helpful post for javafxmobile-plugin users (old javafxports)
https://stackoverflow.com/questions/70331869/problem-when-update-targetsdkversion-to-30-dalvik-javafx

official docs
https://docs.gluonhq.com/javafxports/

**Comment by ctoabidmaqbool** [comment]
@jperedadnr Thanks a lot your provided [solution](https://stackoverflow.com/a/55970138/3956070) works like a charm, I have solved half of my problem using:
![image](https://user-images.githubusercontent.com/10474725/190161739-20ed9914-f996-488c-90d1-2c06e4b5cf4b.png)

But another problem exists here, google now required targetAPILever 31 for app to be uploaded.

I am getting this error:

```
...
...
...
> Task :createMainDexList FAILED
[ant:java] Java Result: 1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createMainDexList'.
> Error: Could not find or load main class com.android.multidex.ClassReferenceListBuilder

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings
```

**Comment by ctoabidmaqbool** [comment]
@johanvos @jperedadnr from android 27, company is porting both dx.jar and d8.jar. But in sdk 31 dx is tottaly removed. Only d8.jar exists there. So now, it's more eazy to solve the problem. E.g. Replace dx.jar to d8.jar.

**Comment by ctoabidmaqbool** [comment]
Can new version of [javafx-mobile-plugin](https://github.com/javafxports/javafxmobile-plugin) be released with this little fix for targetsdk 31+ .
Also if somehow charm down plugins source code

**Comment by ctoabidmaqbool** [comment]
I have find a simple trick, simply copy file form old build-tools to new e.g. dx.jar
![image](https://user-images.githubusercontent.com/10474725/190845441-bc1b4da8-18ac-4712-8912-7905d1cb49d1.png)
