### ISSUE TITLE
App freezes when marking a track as favourite

### ISSUE THREAD

**Issue by stefanlange** [devoxx/MyDevoxxGluon#329]
When I open a track in the app on an iPhone 14 Pro running iOS 16, and mark it a favourite by clicking the heart icon, the app freezes.

**Comment by jperedadnr** [comment]
It is a known issue, the dialog displayed to type the comment before sending the vote is using internally `enterNestedEventLoop` which is causing issues on  iPhone 13 and 14 (same issue as camera view not showing up to scan badges, which could be fixed by removing it)
