### ISSUE TITLE
iOS 16: Feedback on talk crashes app

### ISSUE THREAD

**Issue by bart-blommaerts** [devoxx/MyDevoxxGluon#336]
To reproduce:

- Open app
- Click on talk
- Click on Vote
- Click on Write Some Feedback

App is not longer responsive and needs to be killed forcefully.

Reproduceable on iPhone 12 Pro, running iOS 16.0 (20A362).

**Comment by jperedadnr** [comment]
Can you try the app from TestFlight? The issue should be fixed already.

https://testflight.apple.com/join/fYZeFwBP

**Comment by bart-blommaerts** [comment]
I can confirm. It works on the newer version.

**Comment by jperedadnr** [comment]
Great, thanks for testing!
