### ISSUE TITLE
GitHub OAuth redirect info is shown instead of going back to prev screen

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#349]
GitHub OAuth using Android works but the "Redirect" info is shown instead of the list of talks (Samsung S23)

![Screenshot_20230324_154758](https://user-images.githubusercontent.com/179457/227905911-b2a13ac5-09c1-4670-9959-70d49b00e190.jpg)

**Comment by jperedadnr** [comment]
Fixed with #350
