### ISSUE TITLE
UX Enhancement: show SessionType in overview

### ISSUE THREAD

**Issue by erwin1** [devoxx/MyDevoxxGluon#49]
It's not always very clear what SessionType a talk is related to. It would be nice to visualise it in the overview like this:
![image 1](https://user-images.githubusercontent.com/9695589/39126045-571a3e8c-4701-11e8-9049-414164859e45.png)

**Comment by jperedadnr** [comment]
The OTN app had already implemented a color code for the tracks, and it was reflected as a narrow vertical line to the left in each of the cells of the CharmListView in the Sessions view. 

Enabling this back is easy.

About the header, the CharmListView allows different headers, but so far we are sorting by date, so the headers show the day. We could also sort by track, and the headers could be updated accordingly.  Once headers are sorted by track, the regular cells will be sorted by date.

The only issue will be the need of having a button to sort by one criterium or the other, or add this option to the existing filter popup. Also sorting could be modified to be ascendent or descendent.

**Comment by stephanj** [comment]
We could also consider the following UX approach and not show a track header.

![image](https://user-images.githubusercontent.com/179457/39126696-4b75d828-4703-11e8-8dac-1f3e430115e2.png)

**Comment by erwin1** [comment]
This is fine the way it is currently implemented.

Follow-up of this issue in #68
