### ISSUE TITLE
"broken" QR Code 

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#53]
The attached QR Code could not be scanned by the mobile app.  However other QR Code apps on Android had no problem with it.   Maybe you should consider selecting a different intent?

![image](https://user-images.githubusercontent.com/179457/40049061-011a93da-5834-11e8-9f1f-7bce958ab20f.png)

**Comment by tiainen** [comment]
We've updated Charm Down to 3.8.1 which incorporates an update to the zxing barcode scanning library for android (see https://bitbucket.org/gluon-oss/charm-down/pull-requests/50/upgrade-zxing-barcode-scanning-library-to/diff). We'll see if that improves barcode scanning on android devices.

**Comment by jimmylemmens23** [comment]
#/ 50,- Diner-restaurants the barcode only.
Can i just use it or the asked me barcode. I have only on the box a code inv

**Comment by jimmylemmens23** [comment]
![Image](https://github.com/user-attachments/assets/299c7d9e-0a41-4d47-916a-20308b8b0711)

![Image](https://github.com/user-attachments/assets/ddce9fbe-cce5-4388-81fa-db9ac7497625)
