### ISSUE TITLE
Zoom into image on Android

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#55]
It's almost not possible to zoom into the venue images on Android.   
Does work very well on iOS.

![image](https://user-images.githubusercontent.com/179457/40049322-c4c70214-5834-11e8-9467-8286dc50b31f.png)

**Comment by jperedadnr** [comment]
I didn't realize this issue, and created #62, and provided a fix for it (PR #63)

**Comment by erwin1** [comment]
duplicate of #62
