### ISSUE TITLE
Make use of new CFP backend APIs

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#56]
(Old title: Replace cfp.json with REST calls to get list of upcoming Devoxx events

We should start considering using the https://beta.devoxx.com REST endpoints to get the upcoming Devoxx events instead of cfp.json. These include also the timezone etc.

To get the list of upcoming Devoxx events:  https://beta.voxxeddays.com/backend/api/voxxeddays/events/future/devoxx

Event details:  
https://beta.voxxeddays.com/backend/api/voxxeddays/events/16

This includes the cfpURL field.

However we need to review what info is missing in the beta REST endpoints before we move forward.

**Comment by erwin1** [comment]
Action items:
* use https://beta.devoxx.com/backend/api/voxxeddays/events/future/devoxx instead of cfp.json 
* test what is missing from the new CFP APIs and comment back here to discuss

**Comment by stephanj** [comment]
More details for each event is retrieved via following REST endpoint :  https://beta.devoxx.com/backend/api/voxxeddays/events/2

**Comment by abhinayagarwal** [comment]
@stephanj Are the APIs for retrieving sessions and other details also defined? The `cfpURL` for the events are `null`, making it impossible to test any further.

**Comment by stephanj** [comment]
Thanks for reporting this, I've updated the CFP URL's and api key's.

**Comment by abhinayagarwal** [comment]
@stephanj Previously, the cfpEndpoints used to have "/api" appended to the cfp url.
 
cfpEndpoint: "https://cfp.devoxx.be/api",

In the new backend, we have "cfpURL" instead of "cfpEndpoint" and it points to:

cfpURL: "https://dvbe18.confinabox.com"

Is this expected behaviour?

**Comment by abhinayagarwal** [comment]
@stephanj The new conference API seems to be missing Venue details like venue, address, latitude, longtitude. Is there a different API for the same? I tried searching https://dvbe18.confinabox.com/api and couldn't find anything related.

**Comment by stephanj** [comment]
When you call the even details @ https://beta.devoxx.com/backend/api/voxxeddays/events/2 
You'll find a location id (see below). 

Will provide later today a REST endpoint so you can retrieve the location details via  https://beta.devoxx.com/backend/api/voxxeddays/location/2  

```
{  
   "id":2,
   "name":"Devoxx UK 2017",
   "website":"https://www.devoxx.co.uk/",
   "description":"Devoxx UK returned to London on 11th Ã¢â‚¬â€œ 12th May 2017 and once again welcomed amazing speakers and attendees for the very best developer content and awesome experiences.",
   "imageURL":"https://s3-eu-west-1.amazonaws.com/voxxeddays/webapp/images/a45e9e3a-70b6-4513-b357-4355cce1af79.jpg",
   "scheduleURL":"",
   "eventImagesURL":"",
   "youTubeURL":null,
   "fromDate":"2017-05-10",
   "endDate":"2017-05-11",
   "cfpFromDate":"2000-01-01",
   "cfpEndDate":"2000-01-01",
   "eventType":"DEVOXX",
   "cfpURL":"https://cfp.devoxx.co.uk/api",
   "cfpVersion":"DV17",
   "archived":true,
   "cfpActive":true,
   "importDate":"2018-01-25",
   "scheduleDate":null,
   "locationId":2,
   "locationName":"Business Design Center",
   "timezone":"Europe/London",
   "cfpAdminEmail":null,
   "fromEmail":"info@confinabox.com",
   "committeeEmail":null,
   "bccEmail":null,
   "bugReportEmail":null,
   "githubClientId":null,
   "githubSecret":null,
   "googleClientId":null,
   "googleSecret":null,
   "linkedInClientId":null,
   "linkedInSecret":null,
   "maxProposals":null,
   "owners":[  
   ],
   "tracks":[  
   ],
   "sessionTypes":[  
   ],
   "languages":[  
   ]
}
```

**Comment by stephanj** [comment]
Location REST endpoint available @ https://api.voxxed.com/api/voxxeddays/location/2

**Comment by abhinayagarwal** [comment]
@stephanj The new conference API doesn't seem to return the details about floors. This was used to show the different levels in exhibition map.

**Comment by stephanj** [comment]
Indeed, will add it next week.
Keep you posted.

**Comment by abhinayagarwal** [comment]
@stephanj Hi! Is there any update on conference API?

**Comment by abhinayagarwal** [comment]
It blocks #56 and #73. I can work on other issues for now :+1:

**Comment by stephanj** [comment]
As promised, I've added floor plan images to the event.

Only Devoxx Belgium (for now) has floor plan details which you can collect via 
https://beta.voxxeddays.com/backend/api/voxxeddays/events/31 

![image](https://user-images.githubusercontent.com/179457/44353544-a0426680-a4a7-11e8-8842-4a6f1a37bb40.png)
