### ISSUE TITLE
Old exhibition map images

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#57]
Some mobile apps were showing the 2017 exhibition image maps instead of the ones from 2018.
Johan told me it should use the Gluon (proxy) image storage instead of AWS S3 ?! 

This image below is ok but didn't get updated to the latest version.

![image](https://user-images.githubusercontent.com/179457/40056332-614a07e2-584b-11e8-914d-75d9b66e0d78.png)

**Comment by abhinayagarwal** [comment]
Fixed by PR #103
