### ISSUE TITLE
Use QR Code icon button instead of "unknown" icon

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#67]
In the "My Badges" an unidentifiable icon is used to trigger the QR Code scanner. 
 
![image](https://user-images.githubusercontent.com/179457/40736644-dd4b37a4-643e-11e8-95fe-447bea0ef38c.png)

It would be more intuitive if a QR Code icon was used instead. 

![image](https://user-images.githubusercontent.com/179457/40736698-04a92dec-643f-11e8-9916-4a7f7b0c11a2.png)

**Comment by abhinayagarwal** [comment]
This change has been merged in the master branch.

**Comment by abhinayagarwal** [comment]
Closing issue. Feel free to re-open in case of any discrepancy.
