### ISSUE TITLE
Show session type above group of presentations

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#68]
The only important detail which is missing on the list view are the session types : conference, bof, deep-dive, hands-on lab, tools-in-action, keynotes, etc.

Would be nice if this could be shown in a horizontal bar above each group of related presentations.

![image](https://user-images.githubusercontent.com/179457/40736869-768a9dec-643f-11e8-8326-4dc697913edc.png)

**Comment by abhinayagarwal** [comment]
@stephanj Should the sessions be re-arranged depending on their type?  

For example, in Devoxx Poland, on 20th June 2018, one can find the following sessions with their time and type:

> "Opening Keynote"
> 
> S1 - 09:00
> S2 - 09:30
> 
> "Conference"
> 
> S3 - 11:00
> ...
> S8 - 11:00
> 
> "Quickie Sessions"
> 
> S9   - 12:20
> S10 - 12:20
> S11 - 12:20
> 
> "Conference"
> 
> S12 - 15 - 12:50
> S16 - 20 - 14:00
> S21 - 26 - 15:10
> ....
> 

Is the above session type text correct representation for placement of horizontal bars, or are we supposed to put all sessions with type "conference" together?

**Comment by stephanj** [comment]
Maybe this can be an option in the mobile app, where people can choose to group sessions by type (conference, keynote, etc.) OR by time.  

I personally prefer a sorting by time.

**Comment by abhinayagarwal** [comment]
In case we sort by time, there can be multiple groups of session types at different time. Do we show multiple bars for each group as shown in my previous message?
