### ISSUE TITLE
Merge schedule and favorite actions

### ISSUE THREAD

**Issue by erwin1** [devoxx/MyDevoxxGluon#70]
No one seems to really understand the difference between scheduling and favoring talks. So the proposal is to merge both actions:

- drop the scheduling action + list
- keep the favorite action (heart)
- keep sending the favorite action to the backend
- schedule local notifications for favorite actions like we did for scheduling -> ignore conflicting scheduled talks. the user will get 2 notifications at that time. (additionally, we might add a visual mark in the favorites list to conflicting talks)

Action item:
- @stephanj has to check if it's enough to just send the favorite action

**Comment by abhinayagarwal** [comment]
There is another scenario that I have been thinking about...

In Devoxx when a user logs in and schedules a session, notifications are set for the same to remind them to attend and vote for the session.

Let us consider the same user installs the app in another device (or uninstalls the app and re-install the app on the same device). They log-in, the scheduled sessions are reloaded from Cloudlink and shown in the app. Under such circumstance, would one expect to receive notifications for the sync'd scheduled sessions?

**Comment by stephanj** [comment]
Yes, notifications for the sync'ed sessions would also be expected.

+1 for removing the scheduled sessions logic because that REST call was never actually forwarded to the CFP backend  :)
