### ISSUE TITLE
Redesign welcome screen / conference selector

### ISSUE THREAD

**Issue by erwin1** [devoxx/MyDevoxxGluon#73]
* mimic beta.devoxx.com 
![image](https://user-images.githubusercontent.com/9695589/40940479-3c8069d0-6848-11e8-9e1f-d4aa8988add0.png)

* it can not only include all the conferences, but also general news like 'the cfp for devoxx .. has opened' 
(the news will come from a CFP API)

**Comment by abhinayagarwal** [comment]
Do we have any idea(s) how this should look for wearable?

**Comment by tiainen** [comment]
You can ignore wearable for now.
