### ISSUE TITLE
Sponsor badge scanning improvements

### ISSUE THREAD

**Issue by erwin1** [devoxx/MyDevoxxGluon#75]
* CHANGE: sponsors do NOT have to login using a social network. they select: I'm a sponsor -> select their sponsor -> type the (simple) password -> scan -> badges are synced to CloudLink in 1 list per sponsor
* when making a attendee / sponsor selection, there should be a way to go back
* when already made a choice between attendee / sponsor, there should be a way to change without the need to logout

**Comment by abhinayagarwal** [comment]
@stephanj The list of sponsor was fetched using an endpoint: http://app-259bcaa5-xxxx-xxxx-xxxx-xxxxxxxxxxxx.cleverapps.io. This endpoint doesn't seem to work anymore. Will the list of sponsors for badge scanning come from Devoxx backend or will there be a third party API just like this one?

**Comment by stephanj** [comment]
Not yet.  Will provide something around August.

**Comment by erwin1** [comment]
@abhinayagarwal let's use mock data in CloudLink for now then so we can finish and test this enhancement. Create a follow-up issue to make sure we link the remote function to the actual CFP back-end when it's ready.

**Comment by abhinayagarwal** [comment]
PR #91 is open for review
