### ISSUE TITLE
Ask people to rate the app AFTER the conference

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#85]
To increase the rating of the app in the store, I would ask attendees to rate the app when the conference is finished.  

Similar as the example below.
![image](https://user-images.githubusercontent.com/179457/41899387-9dc98330-792c-11e8-9a6a-480ece285da6.png)

**Comment by abhinayagarwal** [comment]
A new area below the AppBar in SessionsPresenter is added to take in feedback from the users. This can be triggered by sending a silent notification from GCL.

The flow is as follows:

* Ask the user if the like Devoxx app
* If yes, ask them to rate us on AppStore/PlayStore
* If no, ask them to leave us a feedback

Here are some pics:

<img alt="like-devoxx" height=500 src="https://user-images.githubusercontent.com/3197675/42382998-8fb0629e-8153-11e8-8550-80676fd5238e.png">   <img alt="rate-devoxx" height=500  src="https://user-images.githubusercontent.com/3197675/42382996-8f3128e4-8153-11e8-94a5-00829e1b0e12.png">

<img alt="feedback-devoxx" height=500 src="https://user-images.githubusercontent.com/3197675/42382994-8eb63b48-8153-11e8-9ca0-d5cd7613f472.png">   <img alt="feedback" height=500 src="https://user-images.githubusercontent.com/3197675/42382995-8ef04fc2-8153-11e8-8263-f277e52b3df2.png">

If the user is logged in the name and email fields will be automatically filled. 

To accomplish this we would need to create an endpoint to store all the feedback from users.

**Comment by erwin1** [comment]
@stephanj See comment above. Do you want to add a CFP endpoint to capture user feedback?
Otherwise we'll have to fallback to something else. (store in CL, email)

**Comment by stephanj** [comment]
I suggest you mail the feedback instead to info@devoxx.com   Thx!
