### ISSUE TITLE
Cache speakers in Gluon CloudLink (AWS)

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#86]
Can we please also cache the speaker details in the Gluon AWS Cloudlink layer? 
This way we avoid that the actual CFP backend is too slow or mis-configured to handle the load.

![image](https://user-images.githubusercontent.com/179457/41899493-e05e9c58-792c-11e8-80ca-2a74dd9c1c12.png)

**Comment by johanvos** [comment]
fixed by PR84
