### ISSUE TITLE
iPhone X toolbar overlaps with AppBar

### ISSUE THREAD

**Issue by tiainen** [devoxx/MyDevoxxGluon#90]
On iPhone X the native toolbar partially overlaps the application's AppBar, making it hard to press any icons that are added to it.

![69598](https://user-images.githubusercontent.com/4688201/42166663-fa5e2a9a-7e0b-11e8-96c1-00a1abe01c4e.jpg)

**Comment by abhinayagarwal** [comment]
The issue should be resolved by upgrading to GM 5.0.0.

**Comment by johanvos** [comment]
fixed by PR90
