### ISSUE TITLE
Remove mock data for sponsors

### ISSUE THREAD

**Issue by abhinayagarwal** [devoxx/MyDevoxxGluon#98]
We are currently mocking data for sponsors in GCL. We need to remove this mocked data before Devoxx BE.

**Comment by erwin1** [comment]
example response:
`{
    "tenant": {
        "name": "dummyTenantName",
        "slug": "dummyTenantSlug"
    },
    "events": [{
        "name": "dummyEventName",
        "slug": "dummyEventSlug",
        "sponsors": [
        {
            "name": "Microsoft",
            "slug": "microsoft",
            "level": "platinum"
        },
        {
            "name": "Gluon",
            "slug": "gluon",
            "level": "gold"
        },
        {
            "name": "Google",
            "slug": "google",
            "level": "platinum"
        }]
    }]
}`

**Comment by tiainen** [comment]
@abhinayagarwal The sponsors can be now be retrieved from the following endpoint: https://beta.voxxeddays.com/backend/api/voxxeddays/sponsors/{conference.id}

For Devoxx BE: https://beta.voxxeddays.com/backend/api/voxxeddays/sponsors/31

The format is slightly different from the existing mock response, so the model on the client needs some work.

**Comment by abhinayagarwal** [comment]
I have removed mock data from GCL and opened PR #102 for review
